# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go generate ./...
    - go mod download

project_name: supervisord

builds:
  - id: static
    env:
      - CGO_ENABLED=1
    binary: supervisord_static
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "-linkmode external -extldflags -static"
  - env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w"
    binary: supervisord
    flags:
      - -tags=release
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - ./upx.sh

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_Linux_64-bit'
    format: tar.gz
    wrap_in_directory: true
    files:
      - none*

release:
  draft: true
  prerelease: true
  name_template: "{{.ProjectName}}-v{{.Version}}-{{.ShortCommit}}"
